version: '{branch}-{build}'
skip_non_tags: false
platform:
- x86
- x64
init:
- cmd: IF %APPVEYOR_REPO_TAG%==true appveyor UpdateBuild -Version %APPVEYOR_REPO_TAG_NAME%-%APPVEYOR_BUILD_NUMBER%
before_build:
- cmd: >-
    FOR %%I IN (https://web.archive.org/web/20110722120922/http://download.microsoft.com/download/4/7/2/47291d3a-b5b5-4447-8182-4b72b505a603/4918.exe) DO curl -fsS -o %%~nxI %%I

    7z e *.exe

    IF %APPVEYOR_REPO_TAG%==true git checkout v%APPVEYOR_REPO_TAG_NAME%
build_script:
- cmd: build.bat
after_build:
- cmd: 7z a mttty-%Platform%.zip *.exe -x!4918.exe
artifacts:
- path: '*.zip'
  name: mttty
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: mAta4PvnGmRbwfwfIjxhUy0jydgo/+Tfz1upm36muoEP7xsMMEp1JHThqQcit4ta
  artifact: /.*\.zip/
  on:
    APPVEYOR_REPO_TAG: true
