version: '{branch}-{build}'
skip_non_tags: true
platform:
- x86
- x64
init:
- cmd: IF %APPVEYOR_REPO_TAG%==true appveyor UpdateBuild -Version %APPVEYOR_REPO_TAG_NAME%-%APPVEYOR_BUILD_NUMBER%
before_build:
- cmd: >-
    IF %APPVEYOR_REPO_TAG_NAME%==4.00 FOR %%I IN (https://web.archive.org/web/20110722120922/http://download.microsoft.com/download/4/7/2/47291d3a-b5b5-4447-8182-4b72b505a603/4918.exe) DO curl -fsS -o %%~nxI %%I

    IF %APPVEYOR_REPO_TAG_NAME%==4.11 curl -fsS -o mttty.zip "https://web.archive.org/web/20191114075942/https://www.netburner.com/download/mttty-download/?wpdmdl=4555&ind=1539519763381"

    FOR %%I IN (*.exe *.zip) DO 7z e %%I

    DEL /Q *.zip
build_script:
- cmd: >-
    IF %APPVEYOR_REPO_TAG_NAME%==4.00 build.bat

    IF %APPVEYOR_REPO_TAG_NAME%==4.11 C:\msys64\usr\bin\sed.exe -b 's@MSVCR71.dll@msvcrt.dll\x00@' -i *.exe
after_build:
- cmd: >-
    7z a mttty-%Platform%.zip *.exe -x!4918.exe

    IF %APPVEYOR_REPO_TAG_NAME%==4.11 IF %Platform%==x64 DEL /Q *.zip
artifacts:
- path: '*.zip'
  name: mttty
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: mAta4PvnGmRbwfwfIjxhUy0jydgo/+Tfz1upm36muoEP7xsMMEp1JHThqQcit4ta
  artifact: /.*\.zip/
  on:
    APPVEYOR_REPO_TAG: true
